### ISSUE TITLE
大佬，您这个项目怎么用？

### ISSUE THREAD

**Issue by GD2021** [cm9vdA/build-armbian#1]
我刷了ophub的armbian后，把哪部分替换成您的呢？
我的机型是zcube1-max

**Comment by toss-a** [comment]
克隆官方armban构建框架后添加这些文件直接构建,你需要自行构建

**Comment by cm9vdA** [comment]
> 克隆官方armban构建框架后添加这些文件直接构建,你需要自行构建

正解

**Comment by cm9vdA** [comment]
增加了简单的使用说明
https://github.com/cm9vdA/build-armbian/blob/master/README.md
