### ISSUE TITLE
官方armbian里的media和rockchip64的区别

### ISSUE THREAD

**Issue by a520ass** [cm9vdA/build-armbian#2]
大佬，官方armbian里有media和rockchip64，好像rk3399都能用，这个有什么区别吗？

**Comment by cm9vdA** [comment]
两个确实都能用，一开始我编译rk3399的armbian固件时也是用的media配置，抄了Station P1的配置，后来发现开机总是会花屏一下，并且系统内获取不到温度，可能是内核config没有添加TSADC吧，所以后来就切换到rockchip64了。从使用上来说，似乎也没什么明显差别。

media看名字好像是给电视盒子一类的设备用的，主要由150balbes大佬维护

**Comment by a520ass** [comment]
> 两个确实都能用，一开始我编译rk3399的armbian固件时也是用的media配置，抄了Station P1的配置，后来发现开机总是会花屏一下，并且系统内获取不到温度，可能是内核config没有添加TSADC吧，所以后来就切换到rockchip64了。从使用上来说，似乎也没什么明显差别。
> 
> media看名字好像是给电视盒子一类的设备用的，主要由150balbes大佬维护

那应该用rockchip64好一点，media估计是特殊用途

**Comment by toss-a** [comment]
> 两个确实都能用，一开始我编译rk3399的armbian固件时也是用的media配置，抄了Station P1的配置，后来发现开机总是会花屏一下，并且系统内获取不到温度，可能是内核config没有添加TSADC吧，所以后来就切换到rockchip64了。从使用上来说，似乎也没什么明显差别。
> 
> media看名字好像是给电视盒子一类的设备用的，主要由150balbes大佬维护

我使用King3399,使用rockchip64分支内核编译出来的固件在2K分辨率使用HDMI会一直闪烁,并且貌似最新版本USB也全部失效,我不知道大佬你是否是这种情况,但是使用media内核正常,刚开机确实会花屏,但我觉得都无伤大雅

**Comment by cm9vdA** [comment]
> > 两个确实都能用，一开始我编译rk3399的armbian固件时也是用的media配置，抄了Station P1的配置，后来发现开机总是会花屏一下，并且系统内获取不到温度，可能是内核config没有添加TSADC吧，所以后来就切换到rockchip64了。从使用上来说，似乎也没什么明显差别。
> > media看名字好像是给电视盒子一类的设备用的，主要由150balbes大佬维护
> 
> 我使用King3399,使用rockchip64分支内核编译出来的固件在2K分辨率使用HDMI会一直闪烁,并且貌似最新版本USB也全部失效,我不知道大佬你是否是这种情况,但是使用media内核正常,刚开机确实会花屏,但我觉得都无伤大雅

不好意思啊，我现在手上已经没有king3399了。你可以把启动日志发出来看看，或许能有什么发现。
