### ISSUE TITLE
您好，我按着你仓库的这些自己创建的小宝nas编译，每次编译出来img镜像里都没有小宝nas的dtb，这是什么原因呢？

### ISSUE THREAD

**Issue by Lemon1151** [cm9vdA/build-armbian#3]
build/cache/sources/u-boot-worktree/u-boot/v2022.07/arch/arm/dts下是有小宝nas的dts u-boot.dtsi dtb

**Comment by cm9vdA** [comment]
内核的patch加了吗？dts要加两次的

**Comment by Lemon1151** [comment]
> 内核的patch加了吗？dts要加两次的

编译的时候选择内核编译就有dtb了

**Comment by cm9vdA** [comment]
> > 内核的patch加了吗？dts要加两次的
> 
> 编译的时候选择内核编译就有dtb了

哈哈，原来如此
